### ISSUE TITLE
Change pinning to include minor version?

### ISSUE THREAD

**Issue by zklaus** [conda-forge/libunwind-feedstock#19]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Occasionally, minor version upgrades break ABI compatibility. This is known and the run_exports section in the meta.yaml states:
```yaml
    # breaks backwards compatibility sometimes but we trust the maintainers that they were only internal
    # https://abi-laboratory.pro/index.php?view=timeline&l=libunwind
    - {{ pin_subpackage('libunwind', max_pin='x') }}
```
Looking at the release history at [the abi tracker](https://abi-laboratory.pro/index.php?view=timeline&l=libunwind), breakage at minor version updates seems to occur with some frequency, so I wonder:
- What is the advantage of keeping `max_pin` at `x`?
- Should this be reconsidered?

This has surfaced in the Julia package recently. Pinging people involved in that discussion: @wolfv, @jakirkham, @mkitti, @valeriupredoi

**Comment by jakirkham** [comment]
Thoughts on an `x.x` pinning?

**Comment by valeriupredoi** [comment]
I reckon an `x.x` pinning is welcome but I am not sure of the initial reasons why the current pinning is only for major releases ie @zklaus question

> What is the advantage of keeping max_pin at x?

**Comment by matthiasdiener** [comment]
+1 on changing to `x.x` pinning.

**Comment by jakirkham** [comment]
Thanks all! 😄

The next steps here are:

1. ~[Mark the previous build number `broken` ]( https://github.com/conda-forge/admin-requests#mark-packages-as-broken-on-conda-forge )~ (or [fix repodata]( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/tree/master/recipe#readme ) if possible)
2. Add [a migrator]( https://github.com/conda-forge/cfep/blob/main/cfep-09.md#implementation-details ) to [conda-forge-pinning]( https://github.com/conda-forge/conda-forge-pinning-feedstock/tree/master/recipe/migrations )

Edit: As a repodata patch would be preferred

**Comment by jakirkham** [comment]
On 2, please see PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2260 )

Asking about 1 here ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2260#issuecomment-984167792 )

**Comment by jakirkham** [comment]
@zklaus would you be able to take a look at making a repodata patch? This change might be a good example ( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/commit/5898e5b82ddf7bd2ad366e5702ae1c149c6cc7df ). Coincidentally it also sits near a `libunwind` patch we would want to fix

**Comment by zklaus** [comment]
@jakirkham, sorry, I was away for a few days. See conda-forge/conda-forge-repodata-patches-feedstock#199.

**Comment by jakirkham** [comment]
No worries. Thanks Klaus! 😄

**Comment by zklaus** [comment]
With updated `run_exports` in #20, the repodata patch in conda-forge/conda-forge-repodata-patches-feedstock#203, and the migrator from conda-forge/conda-forge-pinning-feedstock#2260 under way (see https://conda-forge.org/status/#libunwind16), this issue is resolved.
